### ISSUE TITLE
Console doesn't work after PC restart

### ISSUE THREAD

**Issue by simonhdg** [orochigalois/Focusdata_bridge#13]
After PC restart, they service runs smoothly, synchronising data too.
But the Console doesn't display log, can't stop/start service.

![image](https://cloud.githubusercontent.com/assets/22547097/26449731/3a11c096-4197-11e7-8c67-494c3c3a26c1.png)
![image](https://cloud.githubusercontent.com/assets/22547097/26449744/4fceefb2-4197-11e7-827f-ae134f064de6.png)

**Comment by orochigalois** [comment]
Root cause: systemtray.exe should "Run as Administrator", otherwise, both WCF and service would act strange. Please refer to:
https://stackoverflow.com/questions/14501748/cannot-open-window-service-on-computer-in-window-application
