### ISSUE TITLE
Bridge issue

### ISSUE THREAD

**Issue by simonhdg** [orochigalois/Focusdata_bridge#17]
Configure:
<add key="CLINIC_USER_MAIL" value="simonhui_1@gmail.com" />
<add key="CLINIC_USER_MAIL" value="simonhui_2@gmail.com" />
<add key="CLINIC_USER_MAIL" value="simonhui_3@gmail.com" />

1, Bridge does not update doctor appointment times (fd_rel_doctor_appointment_time)
2, Why the CREATE_USER in fd_rel_clinic_doctor and fd_doctor is 'simonhui_3@gmail.com'?
3, Duplicated records in fd_doctor and fd_rel_clinic_doctor
![image](https://user-images.githubusercontent.com/22547097/27287207-4b1378d6-5546-11e7-8331-af8ea52713a6.png)

**Comment by orochigalois** [comment]
wrong testcase
